/* Copyright 2018 FromtonRouge
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include "user_tables.h"

const uint16_t PROGMEM g_left_controls_table[64][MAX_ONE_KEYCODE] =
{
    NO_ENTRY,                               // [0]
    _K1(CKC_CASE_INNER_ONCE),               // [1]
    _K1(CKC_CASE_INNER_ONCE),               // [2]
    _K1(CKC_CASE_UPPER_ONCE),               // [3]
    _K1(CKC_CASE_INNER_ONCE),               // [4]
    _K1(CKC_CASE_UPPER_ONCE),               // [5]
    _K1(CKC_CASE_UPPER_ONCE),               // [6]
    _K1(CKC_CASE_UPPER_LOCKED),             // [7]
    _K1(CKC_RESET_SEP_AND_CASE),            // [8]
    _K1(CKC_CASE_NORMAL),                   // [9]
    _K1(CKC_CASE_INNER_LOCKED),             // [10]
    NO_ENTRY,                               // [11]
    _K1(CKC_CASE_UPPER_LOCKED),             // [12]
    NO_ENTRY,                               // [13]
    NO_ENTRY,                               // [14]
    NO_ENTRY,                               // [15]
    _K1(CKC_CASE_INNER_ONCE),               // [16]
    NO_ENTRY,                               // [17]
    NO_ENTRY,                               // [18]
    NO_ENTRY,                               // [19]
    NO_ENTRY,                               // [20]
    NO_ENTRY,                               // [21]
    NO_ENTRY,                               // [22]
    NO_ENTRY,                               // [23]
    _K1(CKC_CAMEL),                         // [24]
    NO_ENTRY,                               // [25]
    NO_ENTRY,                               // [26]
    NO_ENTRY,                               // [27]
    NO_ENTRY,                               // [28]
    NO_ENTRY,                               // [29]
    NO_ENTRY,                               // [30]
    NO_ENTRY,                               // [31]
	_K1(CKC_CASE_INNER_ONCE),               // [32]
    NO_ENTRY,                               // [33]
    NO_ENTRY,                               // [34]
    NO_ENTRY,                               // [35]
    NO_ENTRY,                               // [36]
    NO_ENTRY,                               // [37]
    NO_ENTRY,                               // [38]
    NO_ENTRY,                               // [39]
    NO_ENTRY,                               // [40]
    NO_ENTRY,                               // [41]
    NO_ENTRY,                               // [42]
    NO_ENTRY,                               // [43]
    NO_ENTRY,                               // [44]
    NO_ENTRY,                               // [45]
    NO_ENTRY,                               // [46]
    NO_ENTRY,                               // [47]
    _K1(CKC_CASE_INNER_ONCE),               // [48]
    NO_ENTRY,                               // [49]
    NO_ENTRY,                               // [50]
    NO_ENTRY,                               // [51]
    NO_ENTRY,                               // [52]
    NO_ENTRY,                               // [53]
    NO_ENTRY,                               // [54]
    NO_ENTRY,                               // [55]
    NO_ENTRY,                               // [56]
    NO_ENTRY,                               // [57]
    NO_ENTRY,                               // [58]
    NO_ENTRY,                               // [59]
    NO_ENTRY,                               // [60]
    NO_ENTRY,                               // [61]
    NO_ENTRY,                               // [62]
    NO_ENTRY                                // [63]
};


const uint16_t PROGMEM g_right_controls_table[32][MAX_SYMBOLS] =
{
    NO_ENTRY,                               // [0]
    _S2(_E, _R),                            // [1]
    _S2(_E, _R),                            // [2]
    _S3(_I, _N, _G),                        // [3]
    _S2(_E, _R),                            // [4]
    _S3(_I, _N, _G),                        // [5]
    _S3(_I, _N, _G),                        // [6]
    _S2(_APOS, _M),                         // [7]
    _S2(_APOS, _S),                         // [8]
    _S2(_APOS, _D),                         // [9]
    _S3(_APOS, _V, _E),                     // [10]
    _S3(_APOS, _R, _E),                     // [11]
    _S3(_APOS, _L, _L),                     // [12]
    NO_ENTRY,                               // [13]
    _S3(_N, _APOS, _T),                     // [14]
    NO_ENTRY,                               // [15]
    _S1(_D),                                // [16]
    NO_ENTRY,                               // [17]
    NO_ENTRY,                               // [18]
    NO_ENTRY,                               // [19]
    NO_ENTRY,                               // [20]
    NO_ENTRY,                               // [21]
    _S3(_N, _APOS, _T),                     // [22]
    NO_ENTRY,                               // [23]
    _S1(_D),                                // [24]
    NO_ENTRY,                               // [25]
    NO_ENTRY,                               // [26]
    NO_ENTRY,                               // [27]
    NO_ENTRY,                               // [28]
    NO_ENTRY,                               // [29]
    NO_ENTRY,                               // [30]
    NO_ENTRY                                // [31]
};

const uint16_t PROGMEM g_left_punctuation_table[256][MAX_PUNCTUATION] =
{
    NO_ENTRY, // [0]
    _P1(_APOS), // [1]
    _P1(_DOT),   // [2]
    _P1(_EXLM),  // [3]
    _P1(_LCBR), // [4]
    _P1(_DQUOT), // [5]
    _P1(_GRTR), // [6]
    _P1(_QUES), // [7]
    _P1(_LPRN), // [8]
    _P1(_LESS), // [9]
    _P2(_MINS, _GRTR), // [10]
    _P2(_LESS, _LESS), // [11]
    _P1(_LBRC), // [12]
    NO_ENTRY, // [13]
    _P2(_GRTR, _GRTR), // [14]
    _P1(_HASH), // [15]
    _P1(_PLUS), // [16]
    _P1(_GRV), // [17]
    _P1(_TILD), // [18]
    NO_ENTRY, // [19]
    _P2(_PLUS, _PLUS), // [20]
    NO_ENTRY, // [21]
    _P1(_AMP), // [22]
    _P2(_AMP, _AMP), // [23]
    _P1(_BSLS), // [24]
    NO_ENTRY, // [25]
    _P2(_BSLS, _BSLS), // [26]
    _P1(_AT), // [27]
    NO_ENTRY, // [28]
    NO_ENTRY, // [29]
    NO_ENTRY, // [30]
    NO_ENTRY, // [31]
    _P1(_MINS), // [32]
    NO_ENTRY, // [33]
    _P1(_EQL), // [34]
    _P1(_DLR), // [35]
    _P1(_SLSH), // [36]
    _P2(_SLSH, _SLSH), // [37]
    _P1(_CIRC), // [38]
    _P3(_SLSH, _SLSH, _SLSH), // [39]
    _P2(_MINS, _MINS), // [40]
    NO_ENTRY, // [41]
    _P1(_UNDS), // [42]
    _P2(_DLR, _LPRN), // [43]
    _P2(_SLSH, _ASTR), // [44]
    NO_ENTRY, // [45]
    _P3(_SLSH, _ASTR, _ASTR), // [46]
    _P4(_SLSH, _SLSH, _SLSH, _LESS), // [47]
    _P1(_ASTR), // [48]
    NO_ENTRY, // [49]
    _P1(_PIPE), // [50]
    _P2(_DOT, _ASTR), // [51]
    _P2(_ASTR, _SLSH), // [52]
    NO_ENTRY, // [53]
    NO_ENTRY, // [54]
    _P2(_DLR, _LCBR), // [55]
    _P2(_ASTR, _LPRN), // [56]
    NO_ENTRY, // [57]
    _P2(_PIPE, _PIPE), // [58]
    _P3(_ASTR, _DOT, _ASTR), // [59]
    _P1(_PERC), // [60]
    NO_ENTRY, // [61]
    NO_ENTRY, // [62]
    NO_ENTRY, // [63]
    _P1(CKC_DELWORD), // [64]
    NO_ENTRY, // [65]
    _P2(LSFT(KC_END), KC_DEL), // [66]
    NO_ENTRY, // [67]
    NO_ENTRY, // [68]
    NO_ENTRY, // [69]
    NO_ENTRY, // [70]
    NO_ENTRY, // [71]
    NO_ENTRY, // [72]
    NO_ENTRY, // [73]
    NO_ENTRY, // [74]
    NO_ENTRY, // [75]
    NO_ENTRY, // [76]
    NO_ENTRY, // [77]
    NO_ENTRY, // [78]
    NO_ENTRY, // [79]
    NO_ENTRY, // [80]
    NO_ENTRY, // [81]
    NO_ENTRY, // [82]
    NO_ENTRY, // [83]
    NO_ENTRY, // [84]
    NO_ENTRY, // [85]
    NO_ENTRY, // [86]
    NO_ENTRY, // [87]
    NO_ENTRY, // [88]
    NO_ENTRY, // [89]
    NO_ENTRY, // [90]
    NO_ENTRY, // [91]
    NO_ENTRY, // [92]
    NO_ENTRY, // [93]
    NO_ENTRY, // [94]
    NO_ENTRY, // [95]
    _P2(CKC_DELWORD, CKC_DELWORD), // [96]
    NO_ENTRY, // [97]
    NO_ENTRY, // [98]
    NO_ENTRY, // [99]
    NO_ENTRY, // [100]
    NO_ENTRY, // [101]
    NO_ENTRY, // [102]
    NO_ENTRY, // [103]
    _P2(LSFT(KC_HOME), KC_DEL), // [104]
    NO_ENTRY, // [105]
    _P3(KC_HOME, LSFT(KC_END), KC_DEL), // [106]
    NO_ENTRY, // [107]
    NO_ENTRY, // [108]
    NO_ENTRY, // [109]
    NO_ENTRY, // [110]
    NO_ENTRY, // [111]
    _P2(_ASTR, _ASTR), // [112]
    NO_ENTRY, // [113]
    NO_ENTRY, // [114]
    NO_ENTRY, // [115]
    NO_ENTRY, // [116]
    NO_ENTRY, // [117]
    NO_ENTRY, // [118]
    NO_ENTRY, // [119]
    NO_ENTRY, // [120]
    NO_ENTRY, // [121]
    NO_ENTRY, // [122]
    NO_ENTRY, // [123]
    NO_ENTRY, // [124]
    NO_ENTRY, // [125]
    NO_ENTRY, // [126]
    NO_ENTRY, // [127]
    _P1(_N0), // [128]
    NO_ENTRY, // [129]
    _P1(_N1), // [130]
    _P1(KC_ESC), // [131]
    _P2(_LCBR, _N0), // [132]
    NO_ENTRY, // [133]
    NO_ENTRY, // [134]
    NO_ENTRY, // [135]
    _P1(_N2), // [136]
    NO_ENTRY, // [137]
    _P1(_N3), // [138]
    NO_ENTRY, // [139]
    _P2(_LBRC, _N0), // [140]
    NO_ENTRY, // [141]
    NO_ENTRY, // [142]
    NO_ENTRY, // [143]
    NO_ENTRY, // [144]
    NO_ENTRY, // [145]
    NO_ENTRY, // [146]
    NO_ENTRY, // [147]
    NO_ENTRY, // [148]
    NO_ENTRY, // [149]
    NO_ENTRY, // [150]
    NO_ENTRY, // [151]
    _P2(_LPRN, _N0), // [152]
    NO_ENTRY, // [153]
    NO_ENTRY, // [154]
    NO_ENTRY, // [155]
    NO_ENTRY, // [156]
    NO_ENTRY, // [157]
    NO_ENTRY, // [158]
    NO_ENTRY, // [159]
    _P1(_N4), // [160]
    NO_ENTRY, // [161]
    _P1(_N5), // [162]
    NO_ENTRY, // [163]
    NO_ENTRY, // [164]
    NO_ENTRY, // [165]
    NO_ENTRY, // [166]
    NO_ENTRY, // [167]
    _P1(_N6), // [168]
    NO_ENTRY, // [169]
    _P1(_N7), // [170]
    NO_ENTRY, // [171]
    NO_ENTRY, // [172]
    NO_ENTRY, // [173]
    NO_ENTRY, // [174]
    NO_ENTRY, // [175]
    NO_ENTRY, // [176]
    NO_ENTRY, // [177]
    NO_ENTRY, // [178]
    NO_ENTRY, // [179]
    NO_ENTRY, // [180]
    NO_ENTRY, // [181]
    NO_ENTRY, // [182]
    NO_ENTRY, // [183]
    NO_ENTRY, // [184]
    NO_ENTRY, // [185]
    NO_ENTRY, // [186]
    NO_ENTRY, // [187]
    NO_ENTRY, // [188]
    NO_ENTRY, // [189]
    NO_ENTRY, // [190]
    NO_ENTRY, // [191]
    _P1(_N8), // [192]
    NO_ENTRY, // [193]
    _P1(_N9), // [194]
    NO_ENTRY, // [195]
    NO_ENTRY, // [196]
    NO_ENTRY, // [197]
    NO_ENTRY, // [198]
    NO_ENTRY, // [199]
    _P2(_N1, _N0), // [200]
    NO_ENTRY, // [201]
    _P2(_N1, _N1), // [202]
    NO_ENTRY, // [203]
    NO_ENTRY, // [204]
    NO_ENTRY, // [205]
    NO_ENTRY, // [206]
    NO_ENTRY, // [207]
    NO_ENTRY, // [208]
    NO_ENTRY, // [209]
    NO_ENTRY, // [210]
    NO_ENTRY, // [211]
    NO_ENTRY, // [212]
    NO_ENTRY, // [213]
    NO_ENTRY, // [214]
    NO_ENTRY, // [215]
    NO_ENTRY, // [216]
    NO_ENTRY, // [217]
    NO_ENTRY, // [218]
    NO_ENTRY, // [219]
    NO_ENTRY, // [220]
    NO_ENTRY, // [221]
    NO_ENTRY, // [222]
    NO_ENTRY, // [223]
    _P2(_N1, _N2), // [224]
    NO_ENTRY, // [225]
    _P2(_N1, _N3), // [226]
    NO_ENTRY, // [227]
    NO_ENTRY, // [228]
    NO_ENTRY, // [229]
    NO_ENTRY, // [230]
    NO_ENTRY, // [231]
    _P2(_N1, _N4), // [232]
    NO_ENTRY, // [233]
    _P2(_N1, _N5), // [234]
    NO_ENTRY, // [235]
    NO_ENTRY, // [236]
    NO_ENTRY, // [237]
    NO_ENTRY, // [238]
    NO_ENTRY, // [239]
    NO_ENTRY, // [240]
    NO_ENTRY, // [241]
    NO_ENTRY, // [242]
    NO_ENTRY, // [243]
    NO_ENTRY, // [244]
    NO_ENTRY, // [245]
    NO_ENTRY, // [246]
    NO_ENTRY, // [247]
    NO_ENTRY, // [248]
    NO_ENTRY, // [249]
    NO_ENTRY, // [250]
    NO_ENTRY, // [251]
    NO_ENTRY, // [252]
    NO_ENTRY, // [253]
    NO_ENTRY, // [254]
    NO_ENTRY // [255]
};

const uint16_t PROGMEM g_right_punctuation_table[256][MAX_PUNCTUATION] =
{
    NO_ENTRY, // [0]
    _P1(_APOS), // [1]
    _P1(KC_SPC), // [2]
    _P2(_APOS, KC_LEFT), // [3]
    _P1(_RCBR), // [4]
    _P1(_DQUOT), // [5]
    _P2(_RCBR, KC_LEFT), // [6]
    _P2(_DQUOT, KC_LEFT), // [7]
    _P1(_RPRN), // [8]
    _P1(_GRTR), // [9]
    _P2(_RPRN, KC_LEFT), // [10]
    _P2(_GRTR, KC_LEFT), // [11]
    _P1(_RBRC), // [12]
    NO_ENTRY, // [13]
    _P2(_RBRC, KC_LEFT), // [14]
    _P2(KC_SPC, KC_LEFT), // [15]
    _P1(_DOT), // [16]
    _P2(_APOS, _DOT), // [17]
    _P1(_COLN), // [18]
    _P3(_APOS, _DOT, CKC_DLEFT), // [19]
    _P2(_RCBR, _DOT), // [20]
    _P2(_DQUOT, _DOT), // [21]
    _P3(_RCBR, _DOT, CKC_DLEFT), // [22]
    _P3(_DQUOT, _DOT, CKC_DLEFT), // [23]
    _P2(_RPRN, _DOT), // [24]
    _P2(_ASTR, _SLSH), // [25]
    _P3(_RPRN, _DOT, CKC_DLEFT), // [26]
    _P3(_ASTR, _SLSH, CKC_DLEFT), // [27]
    _P2(_RBRC, _DOT), // [28]
    NO_ENTRY, // [29]
    _P3(_RBRC, _DOT, CKC_DLEFT), // [30]
    NO_ENTRY, // [31]
    _P1(_COMM), // [32]
    _P2(_APOS, _COMM), // [33]
    _P1(_EQL), // [34]
    _P3(_APOS, _COMM, CKC_DLEFT), // [35]
    _P2(_RCBR, _COMM), // [36]
    _P2(_DQUOT, _COMM), // [37]
    _P3(_RCBR, _COMM, CKC_DLEFT), // [38]
    _P3(_DQUOT, _COMM, CKC_DLEFT), // [39]
    _P2(_RPRN, _COMM), // [40]
    _P2(_GRTR, _COMM), // [41]
    _P3(_RPRN, _COMM, CKC_DLEFT), // [42]
    _P3(_GRTR, _COMM, CKC_DLEFT), // [43]
    _P2(_RBRC, _COMM), // [44]
    NO_ENTRY, // [45]
    _P3(_RBRC, _COMM, CKC_DLEFT), // [46]
    NO_ENTRY, // [47]
    _P1(_SCLN), // [48]
    _P2(_APOS, _SCLN), // [49]
    _P2(_COLN, _COLN), // [50]
    _P3(_APOS, _SCLN, CKC_DLEFT), // [51]
    _P2(_RCBR, _SCLN), // [52]
    _P2(_DQUOT, _SCLN), // [53]
    _P3(_RCBR, _SCLN, CKC_DLEFT), // [54]
    _P3(_DQUOT, _SCLN, CKC_DLEFT), // [55]
    _P2(_RPRN, _SCLN), // [56]
    NO_ENTRY, // [57]
    _P3(_RPRN, _SCLN, CKC_DLEFT), // [58]
    NO_ENTRY, // [59]
    _P2(_RBRC, _SCLN), // [60]
    NO_ENTRY, // [61]
    _P3(_RBRC, _SCLN, CKC_DLEFT), // [62]
    NO_ENTRY, // [63]
    _P1(KC_ENT), // [64]
    _P2(_APOS, KC_ENT), // [65]
    _P1(KC_TAB), // [66]
    NO_ENTRY, // [67]
    _P2(_RCBR, KC_ENT), // [68]
    _P2(_DQUOT, KC_ENT), // [69]
    _P3(KC_ENT, _RCBR, CKC_ENTABOVE), // [70]
    NO_ENTRY, // [71]
    _P2(_RPRN, KC_ENT), // [72]
    _P2(_GRTR, KC_ENT), // [73]
    _P3(KC_ENT, _RPRN, CKC_ENTABOVE), // [74]
    NO_ENTRY, // [75]
    _P2(_RBRC, KC_ENT), // [76]
    NO_ENTRY, // [77]
    _P3(KC_ENT, _RBRC, CKC_ENTABOVE), // [78]
    NO_ENTRY, // [79]
    _P2(_DOT, KC_ENT), // [80]
    _P3(_APOS, _DOT, KC_ENT), // [81]
    _P2(_COLN, KC_ENT), // [82]
    NO_ENTRY, // [83]
    _P3(_RCBR, _DOT, KC_ENT), // [84]
    _P3(_DQUOT, _DOT, KC_ENT), // [85]
    NO_ENTRY, // [86]
    NO_ENTRY, // [87]
    _P3(_RPRN, _DOT, KC_ENT), // [88]
    _P3(_ASTR, _SLSH, KC_ENT), // [89]
    NO_ENTRY, // [90]
    NO_ENTRY, // [91]
    _P3(_RBRC, _DOT, KC_ENT), // [92]
    NO_ENTRY, // [93]
    NO_ENTRY, // [94]
    NO_ENTRY, // [95]
    _P2(_COMM, KC_ENT), // [96]
    _P3(_APOS, _COMM, KC_ENT), // [97]
    _P2(_EQL, KC_ENT), // [98]
    NO_ENTRY, // [99]
    _P3(_RCBR, _COMM, KC_ENT), // [100]
    _P3(_DQUOT, _COMM, KC_ENT), // [101]
    NO_ENTRY, // [102]
    NO_ENTRY, // [103]
    _P3(_RPRN, _COMM, KC_ENT), // [104]
    _P3(_GRTR, _COMM, KC_ENT), // [105]
    _P2(KC_END, KC_ENT), // [106]
    NO_ENTRY, // [107]
    _P3(_RBRC, _COMM, KC_ENT), // [108]
    NO_ENTRY, // [109]
    NO_ENTRY, // [110]
    NO_ENTRY, // [111]
    _P2(_SCLN, KC_ENT), // [112]
    _P3(_APOS, _SCLN, KC_ENT), // [113]
    _P3(_COLN, _COLN, KC_ENT), // [114]
    NO_ENTRY, // [115]
    _P3(_RCBR, _SCLN, KC_ENT), // [116]
    _P3(_DQUOT, _SCLN, KC_ENT), // [117]
    NO_ENTRY, // [118]
    NO_ENTRY, // [119]
    _P3(_RPRN, _SCLN, KC_ENT), // [120]
    NO_ENTRY, // [121]
    NO_ENTRY, // [122]
    NO_ENTRY, // [123]
    _P3(_RBRC, _SCLN, KC_ENT), // [124]
    NO_ENTRY, // [125]
    NO_ENTRY, // [126]
    NO_ENTRY, // [127]
    _P1(_N0), // [128]
    NO_ENTRY, // [129]
    _P1(_N1), // [130]
    NO_ENTRY, // [131]
    NO_ENTRY, // [132]
    NO_ENTRY, // [133]
    NO_ENTRY, // [134]
    NO_ENTRY, // [135]
    _P1(_N2), // [136]
    NO_ENTRY, // [137]
    _P1(_N3), // [138]
    NO_ENTRY, // [139]
    NO_ENTRY, // [140]
    NO_ENTRY, // [141]
    NO_ENTRY, // [142]
    NO_ENTRY, // [143]
    NO_ENTRY, // [144]
    NO_ENTRY, // [145]
    NO_ENTRY, // [146]
    NO_ENTRY, // [147]
    NO_ENTRY, // [148]
    NO_ENTRY, // [149]
    NO_ENTRY, // [150]
    NO_ENTRY, // [151]
    NO_ENTRY, // [152]
    NO_ENTRY, // [153]
    NO_ENTRY, // [154]
    NO_ENTRY, // [155]
    NO_ENTRY, // [156]
    NO_ENTRY, // [157]
    NO_ENTRY, // [158]
    NO_ENTRY, // [159]
    _P1(_N4), // [160]
    NO_ENTRY, // [161]
    _P1(_N5), // [162]
    NO_ENTRY, // [163]
    NO_ENTRY, // [164]
    NO_ENTRY, // [165]
    NO_ENTRY, // [166]
    NO_ENTRY, // [167]
    _P1(_N6), // [168]
    NO_ENTRY, // [169]
    _P1(_N7), // [170]
    NO_ENTRY, // [171]
    NO_ENTRY, // [172]
    NO_ENTRY, // [173]
    NO_ENTRY, // [174]
    NO_ENTRY, // [175]
    NO_ENTRY, // [176]
    NO_ENTRY, // [177]
    NO_ENTRY, // [178]
    NO_ENTRY, // [179]
    NO_ENTRY, // [180]
    NO_ENTRY, // [181]
    NO_ENTRY, // [182]
    NO_ENTRY, // [183]
    NO_ENTRY, // [184]
    NO_ENTRY, // [185]
    NO_ENTRY, // [186]
    NO_ENTRY, // [187]
    NO_ENTRY, // [188]
    NO_ENTRY, // [189]
    NO_ENTRY, // [190]
    NO_ENTRY, // [191]
    _P1(_N8), // [192]
    NO_ENTRY, // [193]
    _P1(_N9), // [194]
    NO_ENTRY, // [195]
    NO_ENTRY, // [196]
    NO_ENTRY, // [197]
    NO_ENTRY, // [198]
    NO_ENTRY, // [199]
    _P2(_N1, _N0), // [200]
    NO_ENTRY, // [201]
    _P2(_N1, _N1), // [202]
    NO_ENTRY, // [203]
    NO_ENTRY, // [204]
    NO_ENTRY, // [205]
    NO_ENTRY, // [206]
    NO_ENTRY, // [207]
    NO_ENTRY, // [208]
    NO_ENTRY, // [209]
    NO_ENTRY, // [210]
    NO_ENTRY, // [211]
    NO_ENTRY, // [212]
    NO_ENTRY, // [213]
    NO_ENTRY, // [214]
    NO_ENTRY, // [215]
    NO_ENTRY, // [216]
    NO_ENTRY, // [217]
    NO_ENTRY, // [218]
    NO_ENTRY, // [219]
    NO_ENTRY, // [220]
    NO_ENTRY, // [221]
    NO_ENTRY, // [222]
    NO_ENTRY, // [223]
    _P2(_N1, _N2), // [224]
    NO_ENTRY, // [225]
    _P2(_N1, _N3), // [226]
    NO_ENTRY, // [227]
    NO_ENTRY, // [228]
    NO_ENTRY, // [229]
    NO_ENTRY, // [230]
    NO_ENTRY, // [231]
    _P2(_N1, _N4), // [232]
    NO_ENTRY, // [233]
    _P2(_N1, _N5), // [234]
    NO_ENTRY, // [235]
    NO_ENTRY, // [236]
    NO_ENTRY, // [237]
    NO_ENTRY, // [238]
    NO_ENTRY, // [239]
    NO_ENTRY, // [240]
    NO_ENTRY, // [241]
    NO_ENTRY, // [242]
    NO_ENTRY, // [243]
    NO_ENTRY, // [244]
    NO_ENTRY, // [245]
    NO_ENTRY, // [246]
    NO_ENTRY, // [247]
    NO_ENTRY, // [248]
    NO_ENTRY, // [249]
    NO_ENTRY, // [250]
    NO_ENTRY, // [251]
    NO_ENTRY, // [252]
    NO_ENTRY, // [253]
    NO_ENTRY, // [254]
    NO_ENTRY // [255]
};

const uint16_t PROGMEM g_spaces_ctl_table[2][1] =
{
    NO_ENTRY,                               // [0]
    {KC_ENT},                               // [1]
};
